name = "Yazi"
uuid = "ac312bf5-8f49-49e4-b958-e0a9c6060495"
version = "1.0.0"
authors = ["sandyspiers <sandy.spiers@gmail.com>"]

[yazi]
version = "26.1.22"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
TOML = "1.0.3"
Test = "1.11.0"
julia = "1.6"

[extras]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["TOML", "Test"]
